# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: google_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google_app
  template:
    metadata:
      labels:
        app: google_app
    spec:
      containers:
      - name: django-container
        image: first-django:latest
        ports:
        - containerPort: 3000  # Adjust the port based on your Django app configuration

---

apiVersion: v1
kind: Service
metadata:
  name: your-django-service
spec:
  selector:
    app: google_app
  ports:
    - protocol: TCP
      port: 80  # The port where you want to expose the service
      targetPort: 3000  # Port exposed by your Django app container
  type: LoadBalancer  # Use 'LoadBalancer' for cloud deployments; use 'NodePort' or 'ClusterIP' for other environments
